export const DURATION_ARRAY = [
  [
    { key: "w", icon: "duration-w" },
    { key: "h", icon: "duration-h" },
    { key: "q", icon: "duration-q" },
    { key: "8", icon: "duration-8" },
    { key: "16", icon: "duration-16" },
    { key: "32", icon: "duration-32" },
    { key: "64", icon: "duration-64" },
    { key: "dot", icon: "dot" },
  ],
  [
    { key: "wr", icon: "duration-hr" },
    { key: "hr", icon: "duration-wr" },
    { key: "qr", icon: "duration-qr" },
    { key: "8r", icon: "duration-8r" },
    { key: "16r", icon: "duration-16r" },
    { key: "32r", icon: "duration-32r" },
    { key: "64r", icon: "duration-64r" },
    { key: "barline", icon: "barline" },
    { key: "endline", icon: "endline" },
  ],
];

export const LIFT_ARRAY = [
  [
    { key: "flat", icon: "flat" },
    { key: "reset", icon: "reset" },
    { key: "sharp", icon: "sharp" },
  ],
  [
    { key: "double-flat", icon: "double-flat" },
    { key: "clear", icon: "clear" },
    { key: "double-sharp", icon: "double-sharp" },
  ],
];
export const LIFT_ARRAY_ONE = [
  { key: "flat", icon: "flat" },
  { key: "reset", icon: "reset", width: 45 },
  { key: "sharp", icon: "sharp" },
  { key: "double-flat", icon: "double-flat" },
  { key: "clear", icon: "clear", width: 45 },
  { key: "double-sharp", icon: "double-sharp" },
];

export const LIFT_MAP = {
  flat: "b",
  "double-flat": "bb",
  sharp: "#",
  "double-sharp": "##",
  reset: "n",
};

export const CLEF_ARRAY = [
  { key: "p", icon: "clef-p" },
  { key: "g", icon: "clef-g" },
  { key: "f", icon: "clef-f" },
  { key: "c", icon: "clef-c" },
];
export const CLEF_MAP = {
  g: "treble",
  f: "bass",
  c: "alto",
};

export const KEY_ARRAY = [
  { key: "b", icon: "key-b" },
  { key: "2b", icon: "key-2b" },
  { key: "3b", icon: "key-3b" },
  { key: "4b", icon: "key-4b" },
  { key: "5b", icon: "key-5b" },
  { key: "6b", icon: "key-6b" },
  { key: "7b", icon: "key-7b" },
  { key: "j", icon: "key-j" },
  { key: "2j", icon: "key-2j" },
  { key: "3j", icon: "key-3j" },
  { key: "4j", icon: "key-4j" },
  { key: "5j", icon: "key-5j" },
  { key: "6j", icon: "key-6j" },
  { key: "7j", icon: "key-7j" },
  { key: "reset", icon: "key-reset" },
];
export const KEY_MAP = {
  b: "F",
  "2b": "Bb",
  "3b": "Eb",
  "4b": "Ab",
  "5b": "Db",
  "6b": "Gb",
  "7b": "Cb",
  j: "G",
  "2j": "D",
  "3j": "A",
  "4j": "E",
  "5j": "B",
  "6j": "F#",
  "7j": "C#",
};

export const SPECIAL_ICONS = [
  { key: "w", icon: "duration-w" },
  { key: "h", icon: "duration-h" },
  { key: "q", icon: "duration-q" },
  { key: "8", icon: "duration-8" },
  { key: "16", icon: "duration-16" },
  { key: "32", icon: "duration-32" },
  { key: "64", icon: "duration-64" },
  { key: "wr", icon: "duration-wr" },
  { key: "hr", icon: "duration-hr" },
  { key: "qr", icon: "duration-qr" },
  { key: "8r", icon: "duration-8r" },
  { key: "16r", icon: "duration-16r" },
  { key: "32r", icon: "duration-32r" },
  { key: "64r", icon: "duration-64r" },
  { key: "dot", icon: "dot" },
  { key: "barline", icon: "barline" },
  { key: "endline", icon: "endline" },
  { key: "key-b", icon: "key-b" },
  { key: "key-2b", icon: "key-2b" },
  { key: "key-3b", icon: "key-3b" },
  { key: "key-4b", icon: "key-4b" },
  { key: "key-5b", icon: "key-5b" },
  { key: "key-6b", icon: "key-6b" },
  { key: "key-7b", icon: "key-7b" },
  { key: "key-j", icon: "key-j" },
  { key: "key-2j", icon: "key-2j" },
  { key: "key-3j", icon: "key-3j" },
  { key: "key-4j", icon: "key-4j" },
  { key: "key-5j", icon: "key-5j" },
  { key: "key-6j", icon: "key-6j" },
  { key: "key-7j", icon: "key-7j" },
  { key: "cj", icon: "cj" },
  { key: "dj", icon: "dj" },
  { key: "ej", icon: "ej" },
  { key: "fj", icon: "fj" },
  { key: "gj", icon: "gj" },
  { key: "aj", icon: "aj" },
  { key: "bj", icon: "bj" },
  { key: "cb", icon: "cb" },
  { key: "db", icon: "db" },
  { key: "eb", icon: "eb" },
  { key: "fb", icon: "fb" },
  { key: "gb", icon: "gb" },
  { key: "ab", icon: "ab" },
  { key: "bb", icon: "bb" },
  { key: "caps-cj", icon: "caps-cj" },
  { key: "caps-dj", icon: "caps-dj" },
  { key: "caps-ej", icon: "caps-ej" },
  { key: "caps-fj", icon: "caps-fj" },
  { key: "caps-gj", icon: "caps-gj" },
  { key: "caps-aj", icon: "caps-aj" },
  { key: "caps-bj", icon: "caps-bj" },
  { key: "caps-cb", icon: "caps-cb" },
  { key: "caps-db", icon: "caps-db" },
  { key: "caps-eb", icon: "caps-eb" },
  { key: "caps-fb", icon: "caps-fb" },
  { key: "caps-gb", icon: "caps-gb" },
  { key: "caps-ab", icon: "caps-ab" },
  { key: "caps-bb", icon: "caps-bb" },
  // { key: "chord-1", icon: "chord-1" },
  // { key: "chord-2", icon: "chord-2" },
  // { key: "chord-3", icon: "chord-3" },
  // { key: "chord-4", icon: "chord-4" },
  // { key: "chord-5", icon: "chord-5" },
  // { key: "chord-6", icon: "chord-6" },
  // { key: "chord-7", icon: "chord-7" },
  { key: "chord-o", icon: "chord-o" },
  { key: "chord-oj", icon: "chord-oj" },
  { key: "chord-53", icon: "chord-53" },
  { key: "chord-663", icon: "chord-663" },
  { key: "chord-6", icon: "chord-6" },
  { key: "chord-64", icon: "chord-64" },
  { key: "chord-7", icon: "chord-7" },
  { key: "chord-65", icon: "chord-65" },
  { key: "chord-43", icon: "chord-43" },
  { key: "chord-422", icon: "chord-422" },
  { key: "chord-2", icon: "chord-2" },
];
