const keys = () => {
  return {
    numAndEn: [
      [
        getKey("1", "1001"),
        getKey("2", "1002"),
        getKey("3", "1003"),
        getKey("4", "1004"),
        getKey("5", "1005"),
        getKey("6", "1006"),
        getKey("7", "1007"),
        getKey("8", "1008"),
        getKey("9", "1009"),
        getKey("0", "1000"),
      ],
      [
        getKey("Q", "1010"),
        getKey("W", "1011"),
        getKey("E", "1012"),
        getKey("R", "1013"),
        getKey("T", "1014"),
        getKey("Y", "1015"),
        getKey("U", "1016"),
        getKey("I", "1017"),
        getKey("O", "1018"),
        getKey("P", "1019"),
      ],
      [
        getKey("A", "1020"),
        getKey("S", "1021"),
        getKey("D", "1022"),
        getKey("F", "1023"),
        getKey("G", "1024"),
        getKey("H", "1025"),
        getKey("J", "1026"),
        getKey("K", "1027"),
        getKey("L", "1028"),
      ],
      [
        getKey("Z", "1030"),
        getKey("X", "1031"),
        getKey("C", "1032"),
        getKey("V", "1033"),
        getKey("B", "1034"),
        getKey("N", "1035"),
        getKey("M", "1036"),
      ],
      [
        getKey("*", "1001"),
        getKey(".", "1002"),
        getKey(",", "1003"),
        getKey("-", "1004"),
        getKey("/", "1005"),
        getKey("(", "1006"),
        getKey(")", "1007"),
      ],
      [
        getKey(Constants.keyConstants.caps, "1340"),
        getKey(Constants.keyConstants.space, "1342"),
        getKey(Constants.keyConstants.backspace, "1344"),
      ],
    ],
    numAndEnCaps: [
      [
        getKey("1", "1001"),
        getKey("2", "1002"),
        getKey("3", "1003"),
        getKey("4", "1004"),
        getKey("5", "1005"),
        getKey("6", "1006"),
        getKey("7", "1007"),
        getKey("8", "1008"),
        getKey("9", "1009"),
        getKey("0", "1000"),
      ],
      [
        getKey("q", "1010"),
        getKey("w", "1011"),
        getKey("e", "1012"),
        getKey("r", "1013"),
        getKey("t", "1014"),
        getKey("y", "1015"),
        getKey("u", "1016"),
        getKey("i", "1017"),
        getKey("o", "1018"),
        getKey("p", "1019"),
      ],
      [
        getKey("a", "1020"),
        getKey("s", "1021"),
        getKey("d", "1022"),
        getKey("f", "1023"),
        getKey("g", "1024"),
        getKey("h", "1025"),
        getKey("j", "1026"),
        getKey("k", "1027"),
        getKey("l", "1028"),
      ],
      [
        getKey("z", "1030"),
        getKey("x", "1031"),
        getKey("c", "1032"),
        getKey("v", "1033"),
        getKey("b", "1034"),
        getKey("n", "1035"),
        getKey("m", "1036"),
      ],
      [
        getKey("*", "1001"),
        getKey(".", "1002"),
        getKey(",", "1003"),
        getKey("-", "1004"),
        getKey("/", "1005"),
        getKey("(", "1006"),
        getKey(")", "1007"),
      ],
      [
        getKey(Constants.keyConstants.caps, "1340"),
        getKey(Constants.keyConstants.space, "1342"),
        getKey(Constants.keyConstants.backspace, "1344"),
      ],
    ],
    chord: [
      [
        getKey("Major Triad", "1050"),
        getKey("Minor Triad", "1051"),
        getKey("Augmented Triad", "1052"),
        getKey("Diminished Triad", "1053"),
      ],
      [
        getKey("Dominant 7th", "1060"),
        getKey("Major 7th", "1061"),
        getKey("Minor 7th", "1062"),
        getKey("Minor-major 7th", "1063"),
      ],
      [
        getKey("Minor-major 7th", "1070"),
        getKey("Diminished 7th", "1071"),
        getKey("Augmented 7th", "1072"),
        getKey("Augmented-major 7th", "1073"),
      ],
      [
        getKey("Suspended 2nd", "1080"),
        getKey("Suspended 4th", "1081"),
        getKey("Dominant 7th,Sus. 4th", "1082"),
      ],
      [
        getKey(Constants.keyConstants.caps, "1090"),
        getKey("Ⅰ", "1091"),
        getKey("Ⅱ", "1092"),
        getKey("Ⅲ", "1093"),
        getKey("Ⅳ", "1094"),
        getKey("Ⅴ", "1095"),
        getKey("Ⅵ", "1096"),
        getKey("Ⅶ", "1097"),
      ],
      [
        getKey("0", "1100", { source: "chord-o", target: "chord-o" }),
        getKey("0", "1100", { source: "chord-oj", target: "chord-oj" }),
        getKey("5", "1101", { source: "chord-53", target: "chord-53" }),
        getKey("6", "1102", { source: "chord-663", target: "chord-6" }),
        getKey("6", "1103", { source: "chord-64", target: "chord-64" }),
        getKey("7", "1104", { source: "chord-7", target: "chord-7" }),
        getKey("6", "1105", { source: "chord-65", target: "chord-65" }),
        getKey("4", "1106", { source: "chord-43", target: "chord-43" }),
        getKey("2", "1107", { source: "chord-422", target: "chord-2" }),
      ],
      [
        // getKey(Constants.keyConstants.previous, "1201"),
        getKey(Constants.keyConstants.space, "1202"),
        // getKey(Constants.keyConstants.next, "1203"),
        getKey(Constants.keyConstants.backspace, "1204"),
      ],
    ],
    chordCaps: [
      [
        getKey("Major Triad", "1050"),
        getKey("Minor Triad", "1051"),
        getKey("Augmented Triad", "1052"),
        getKey("Diminished Triad", "1053"),
      ],
      [
        getKey("Dominant 7th", "1060"),
        getKey("Major 7th", "1061"),
        getKey("Minor 7th", "1062"),
        getKey("Minor-major 7th", "1063"),
      ],
      [
        getKey("Minor-major 7th", "1070"),
        getKey("Diminished 7th", "1071"),
        getKey("Augmented 7th", "1072"),
        getKey("Augmented-major 7th", "1073"),
      ],
      [
        getKey("Suspended 2nd", "1080"),
        getKey("Suspended 4th", "1081"),
        getKey("Dominant 7th,Sus. 4th", "1082"),
      ],
      [
        getKey(Constants.keyConstants.caps, "1090"),
        getKey("ⅰ", "1091"),
        getKey("ⅱ", "1092"),
        getKey("ⅲ", "1093"),
        getKey("ⅳ", "1094"),
        getKey("ⅴ", "1095"),
        getKey("ⅵ", "1096"),
        getKey("ⅶ", "1097"),
      ],
      [
        getKey("0", "1100", { source: "chord-o", target: "chord-o" }),
        getKey("0", "1100", { source: "chord-oj", target: "chord-oj" }),
        getKey("5", "1101", { source: "chord-53", target: "chord-53" }),
        getKey("6", "1102", { source: "chord-663", target: "chord-6" }),
        getKey("6", "1103", { source: "chord-64", target: "chord-64" }),
        getKey("7", "1104", { source: "chord-7", target: "chord-7" }),
        getKey("6", "1105", { source: "chord-65", target: "chord-65" }),
        getKey("4", "1106", { source: "chord-43", target: "chord-43" }),
        getKey("2", "1107", { source: "chord-422", target: "chord-2" }),
      ],
      [
        // getKey(Constants.keyConstants.previous, "1201"),
        getKey(Constants.keyConstants.space, "1202"),
        // getKey(Constants.keyConstants.next, "1203"),
        getKey(Constants.keyConstants.backspace, "1204"),
      ],
    ],
    mode: [
      [getKey("Major", "1210"), getKey("Natural Minor", "1211")],
      [getKey("Harmonic Minor", "1220"), getKey("Melodic Minor", "1221")],
      [
        getKey("lonian", "1230"),
        getKey("Dorian", "1231"),
        getKey("Phrygian", "1232"),
        getKey("Lydian", "1233"),
      ],
      [
        getKey("Mixolydian", "1240"),
        getKey("Aeolian", "1241"),
        getKey("Aeolian", "1242"),
      ],
      [
        // getKey(Constants.keyConstants.caps, "1340"),
        // getKey(Constants.keyConstants.previous, "1341", { col: 5 }),
        getKey(Constants.keyConstants.space, "1342"),
        // getKey(Constants.keyConstants.next, "1343", { col: 5 }),
        getKey(Constants.keyConstants.backspace, "1344"),
      ],
    ],
    interval: [
      [
        getKey("d2", "1260"),
        getKey("d3", "1261"),
        getKey("d4", "1262"),
        getKey("d5", "1263"),
        getKey("d6", "1264"),
        getKey("d7", "1265"),
        getKey("d8", "1266"),
      ],
      [
        getKey("m2", "1270"),
        getKey("m3", "1271"),
        getKey("m6", "1272"),
        getKey("m7", "1273"),
      ],
      [
        getKey("M2", "1280"),
        getKey("M3", "1281"),
        getKey("P4", "1282"),
        getKey("P5", "1283"),
        getKey("M6", "1284"),
        getKey("M7", "1285"),
        getKey("P8", "1286"),
      ],
      [
        getKey("A2", "1290"),
        getKey("A3", "1291"),
        getKey("A4", "1292"),
        getKey("A5", "1293"),
        getKey("A6", "1294"),
        getKey("A7", "1295"),
        getKey("A8", "1296"),
      ],
      [
        // getKey(Constants.keyConstants.caps, "1340"),
        // getKey(Constants.keyConstants.previous, "1341", { col: 5 }),
        getKey(Constants.keyConstants.space, "1342"),
        // getKey(Constants.keyConstants.next, "1343", { col: 5 }),
        getKey(Constants.keyConstants.backspace, "1344"),
      ],
    ],
    letter: [
      [
        getKey("C#", "1310", { source: "caps-cj" }),
        getKey("D#", "1311", { source: "caps-dj" }),
        getKey("E#", "1312", { source: "caps-ej" }),
        getKey("F#", "1313", { source: "caps-fj" }),
        getKey("G#", "1314", { source: "caps-gj" }),
        getKey("A#", "1315", { source: "caps-aj" }),
        getKey("B#", "1316", { source: "caps-bj" }),
      ],
      [
        getKey("C", "1320", { source: "caps-c" }),
        getKey("D", "1321", { source: "caps-d" }),
        getKey("E", "1322", { source: "caps-e" }),
        getKey("F", "1323", { source: "caps-f" }),
        getKey("G", "1324", { source: "caps-g" }),
        getKey("A", "1325", { source: "caps-a" }),
        getKey("B", "1326", { source: "caps-b" }),
      ],
      [
        getKey("Cb", "1330", { source: "caps-cb" }),
        getKey("Db", "1331", { source: "caps-db" }),
        getKey("Eb", "1332", { source: "caps-eb" }),
        getKey("Fb", "1333", { source: "caps-fb" }),
        getKey("Gb", "1334", { source: "caps-gb" }),
        getKey("Ab", "1335", { source: "caps-ab" }),
        getKey("Bb", "1336", { source: "caps-bb" }),
      ],
      [
        getKey(Constants.keyConstants.caps, "1340"),
        // getKey(Constants.keyConstants.previous, "1341", { col: 5 }),
        getKey(Constants.keyConstants.space, "1342"),
        // getKey(Constants.keyConstants.next, "1343", { col: 5 }),
        getKey(Constants.keyConstants.backspace, "1344"),
      ],
    ],
    letterCaps: [
      [
        getKey("c#", "1310", { source: "cj" }),
        getKey("d#", "1311", { source: "dj" }),
        getKey("e#", "1312", { source: "ej" }),
        getKey("f#", "1313", { source: "fj" }),
        getKey("g#", "1314", { source: "gj" }),
        getKey("a#", "1315", { source: "aj" }),
        getKey("b#", "1316", { source: "bj" }),
      ],
      [
        getKey("c", "1320", { source: "c" }),
        getKey("d", "1321", { source: "d" }),
        getKey("e", "1322", { source: "e" }),
        getKey("f", "1323", { source: "f" }),
        getKey("g", "1324", { source: "g" }),
        getKey("a", "1325", { source: "a" }),
        getKey("b", "1326", { source: "b" }),
      ],
      [
        getKey("cb", "1330", { source: "cb" }),
        getKey("db", "1331", { source: "db" }),
        getKey("eb", "1332", { source: "eb" }),
        getKey("fb", "1333", { source: "fb" }),
        getKey("gb", "1334", { source: "gb" }),
        getKey("ab", "1335", { source: "ab" }),
        getKey("bb", "1336", { source: "bb" }),
      ],
      [
        getKey(Constants.keyConstants.caps, "1340"),
        // getKey(Constants.keyConstants.previous, "1341", { col: 5 }),
        getKey(Constants.keyConstants.space, "1342"),
        // getKey(Constants.keyConstants.next, "1343", { col: 5 }),
        getKey(Constants.keyConstants.backspace, "1344"),
      ],
    ],
  };
};

function getKey(name, key, extras = {}) {
  const { col, source, target } = extras;
  return {
    name: name,
    key: name,
    col,
    source,
    target: target || source,
  };
}

const Constants = {
  keyConstants: {
    caps: "CAPS",
    space: "Space",
    previous: "Previous",
    next: "Next",
    backspace: "Backspace",
  },
};

export default keys();
